- templates/manager/instructions.html
Fixes some spelling errors and removes unnecessary line breaks
> Correct instructions

- manager/models.py
Bug Fixes:
* Updated the URL regex to be pick up on multiple matches per line by making the non-capture matching group less greedy.
> Updated url regex

- manager/forms.py
- manager/views.py
- templates/manager/email-update.html
Enhancements:
* Added ability to fill out the instant form field by providing `email_id` in the GET parameters.
* Added a link to the instant send view from the email update view that fills out the form to send an instant preview of the current email.
> Instant send updates

- manager/management/commands/recipient-importers.py
Bug Fixes:
* Updates the importers to use the Django 1.11 format for arguments
* Updates the script's use of `transaction.commit_unless_managed` to `transaction.commit` as `commit_unless_managed` is no longer used in Django.
> Hf importers

- manager/models.py
- templates/manager/email-instance.html
Enhancements:
* Reorganizes the stats in the instance view.
* Adds the `total_time` property to instances for easy access to how long the email took to send.
> Formatting update

- manager/views.py
Enhancements:
* Updated the create recipient group from opens and clicks features to be more efficient when writing to the database.
> Fix group create

- manager/views.py
Bug Fixes:
* Fixes a broken double list comprehension by just taking care of it in two loops.
> Removed double list comprehension and just did it with two loops

- manager/views.py
Bug Fixes:
* Adds additional checks to URLs before forwarding the user. This is to prevent hijacked URLs from forwarding to malicious destinations.
> Redirect Changes

- manager/forms.py
- manager/management/commands/import-emails.py
- manager/utils.py
- manager/views.py
Enhancements:
* Adds the "Remove missing recipients" option to the recipient importer. This will remove recipients that are not in the uploaded CSV.
Bug Fixes:
* Fixed a bug where CSV importer doesn't properly update the `SubprocessStatus` object when the import finishes, causing the "Completed" status to never be achieved.
> Added remove stale option to importer and fixed subprocess brokeness

- templates/manager/recipientgroups.html
Bug Fix:
* Make sure the live recipient groups are searched when executing a search on that view.
> Fixed issue with search not working right on recipient groups

- manager/views.py
- templates/manager/emails.html
Bug Fixes:
* Updated sorting logic to ensure all data types properly sort by using the appropriate `-field_name` method of descending order by statements. Fixes #42.
> Modified date sort

- manager/views.py
- templates/manager/emails.html
- templates/manager/recipientgroups.html
Bug Fixes:
* Updated to that sort and order params persist through paging.
> Updated paging to keep order and sort params

- manager/urls.py
- manager/views.py
- templates/manager/recipientgroup-update.html
Enhancements:
* Added the ability to export a recipient group as a CSV file.
> Added button to allow for recipient group export

- settings_local.template.py
> Updated template with new template for logging

- manager/views.py
Bug Fixes:
* Adds some wiggle room to URL verification for click tracking, while still ensuring the URLs are at least valid URLs we've sent out in emails.
> URL Verification

- manager/models.py
- templates/manager/email-instance.html
Enhancements:
* Added some additional reporting stats to the `Instance` model and the `InstanceDetail` view.
> Additional properties

- manager/models.py
- manager/views.py
- templates/manager/instructions.html
Enhancements:
* Added property and view that allows the next week of emails to be displayed.
> Looking ahead

- manager/models.py
Bug Fixes:
* Simplified the query ran to get click stats, offloading some of the processing logic to the database.
> Removed the for loops

- manager/views.py
Bug Fix:
* Fixed a fat finger copy/paste which messed up the email list view.
> Corrected function name

- manager/management/commands/recipient-importers.py
Bug Fixes:
* Updated the syntax used on the `INSERT INTO ... ON DUPLICATE KEY UPDATE` statement in our recipient group importers.
> Importers Update

- manager/views.py
Updated the URL redirect view to use a `get_or_create` to check for an existing URLClick for the given URL and recipient before saving.
Resolves #98 
Tested in Dev.
**Checklist:**
> Prevent multiple URLClick object creations per recipient

- manager/management/commands/import-emails.py
- manager/utils.py
- manager/views.py
Makes various improvements to the syntax and structure of the import loop to avoid off-by-one errors that's causing the first line of the import file to be skipped - even when it shouldn't. Removes special characters by processing the entire CSV file as a string through a regex before pushing it into a string buffer and continuing processing as usual.
Also improves output routing by using `stderr` when possible instead of just printing to the console.
Change is in DEV and QA and has been tested in both.
**Checklist:**
> Hf importer fix

- manager/models.py
Adds a catch all phrase to the email send so that _any_ exception thrown is caught and written to the recipient detail object and the thread can close out gracefully.
We had issues with threads not closing correctly because exceptions were being thrown that weren't being caught by our previous catch all.
Changes have been tested in QA by sending an email to valid and invalid email addresses.
**Checklist:**
> Gotta Catch 'em All

- manager/management/commands/import-emails.py
- manager/utils.py
Makes a number of optimizations to the CSV Importer for importing recipients. Based on local testing, these changes significantly reduce the import time on first insert and updates:
| Import Type | Reduction in Import Time |
|---|---|
| First Time Import  - Emails Only | -81.5% |
| Second Import - Emails Only | -84% |
| First Time Import - Emails and Attributes | -70% |
| Second Time Import - Emails and Attributes | -72% |
We were seeing larger CSV take a significant amount of time to import. All of the test results above were conducted importing CSVs with 150,000 records. Some anecdotal testing was done on much smaller CSVs, and there is a noticeable increase in performance.
The speed tests conducted above were …
> Importer optimizations

- manager/models.py
- manager/templatetags/filters.py
- manager/views.py
- templates/manager/campaign-stats.html
Corrected a division by zero issue on the stats page, as well as making sure all stats are rounded to 2 decimal places.
Changes are available for review in DEV and QA.
**Checklist:**
> Hotfixes for Stats

- manager/models.py
Updated to make sure we use the `recipients` property on the `Email` model.
This property is what was updated to support sending to segments.
Changes have been tested in QA.
**Checklist:**
> Updated logic to use recipients property

- manager/models.py
- manager/utilities/email_message.py
- Updated Recipients' attributes to not have non-ASCII content stripped out when retrieved.
- Added soup-ify-ing step to `EmailMessage.attach_html()`.  This is a just-in-case, hardening step more than anything; there are some comments in the code explaining why.
Resolves #139 
Tested in dev.
**Checklist:**
> More encoding-related updates

- requirements.txt
- setup.py
Updates to pip packages. Resolves #138 and #141 
Keeping the app dependencies up to date for security reasons.
Changes are available for review in DEV and QA.
**Checklist:**
> Updated django and python-ldap
